"""Create initial tables

Revision ID: 2de8919186a1
Revises: 
Create Date: 2026-09-15 15:49:20.193432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de8919186a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único del usuario'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nombre de usuario único'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Correo electrónico único'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='Nombre completo del usuario'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Contraseña hasheada con bcrypt'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL de la imagen de perfil'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False, comment='Rol del usuario: admin o user'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si el usuario está activo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la obra'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Título de la obra'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción de la obra'),
    sa.Column('media_type', sa.Enum('BOOK', 'MOVIE', name='media_type'), nullable=False, comment='Tipo de obra: book o movie'),
    sa.Column('genre', sa.Enum('FICCION', 'CIENCIA_FICCION', 'FANTASIA', 'MISTERIO', 'ROMANCE', 'TERROR', 'HISTORICO', 'AUTOAYUDA', 'DISTOPICO', 'REALISMO_MAGICO', 'JUVENIL', 'CLASICO', 'POESIA', 'NO_FICCION', 'BIOGRAFIA', 'ENSAYO', 'ACCION', 'COMEDIA', 'DRAMA', 'THRILLER', 'SUSPENSE', 'DOCUMENTAL', 'ANIMACION', 'ANIME', 'AVENTURA', name='genre'), nullable=False, comment='Género de la obra'),
    sa.Column('author', sa.String(length=200), nullable=True, comment='Autor del libro o director de la película'),
    sa.Column('release_date', sa.Date(), nullable=True, comment='Fecha de lanzamiento'),
    sa.Column('poster_url', sa.String(length=500), nullable=True, comment='URL de la portada/poster'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint('media_type IS NOT NULL', name='ck_works_media_type_not_null'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_title'), 'works', ['title'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID único de la reseña'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Puntuación de 1 a 5 estrellas'),
    sa.Column('content', sa.Text(), nullable=True, comment='Contenido texto de la reseña'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID del usuario que escribió la reseña'),
    sa.Column('work_id', sa.Integer(), nullable=False, comment='ID de la obra reseñada'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Fecha de última actualización'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_work_id'), 'reviews', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_work_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_works_title'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
