from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class MediaType(str, Enum):
    BOOK = "BOOK"
    MOVIE = "MOVIE"


class GenreEnum(str, Enum):
    FICCION = "FICCION"
    CIENCIA_FICCION = "CIENCIA_FICCION"
    FANTASIA = "FANTASIA"
    MISTERIO = "MISTERIO"
    ROMANCE = "ROMANCE"
    TERROR = "TERROR"
    HISTORICO = "HISTORICO"
    AUTOAYUDA = "AUTOAYUDA"
    DISTOPICO = "DISTOPICO"
    REALISMO_MAGICO = "REALISMO_MAGICO"
    JUVENIL = "JUVENIL"
    CLASICO = "CLASICO"
    POESIA = "POESIA"
    NO_FICCION = "NO_FICCION"
    BIOGRAFIA = "BIOGRAFIA"
    ENSAYO = "ENSAYO"
    ACCION = "ACCION"
    COMEDIA = "COMEDIA"
    DRAMA = "DRAMA"
    THRILLER = "THRILLER"
    SUSPENSE = "SUSPENSE"
    DOCUMENTAL = "DOCUMENTAL"
    ANIMACION = "ANIMACION"
    ANIME = "ANIME"
    AVENTURA = "AVENTURA"
